image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    # or with yarn:
    #- .yarn

stages:
  - build

before_script:
  - npm ci --cache .npm --prefer-offline

eas-build:
  stage: build
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_TOKEN
    - EAS_NO_VCS=1 npx eas-cli build -p android --non-interactive --profile preview