variables: 
  USERNAME: $EXPO_USERNAME
  TOKEN: $EXPO_TOKEN
  
image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    # or with yarn:
    #- .yarn

stages:
  - build

before_script:
  - npm ci --cache .npm
  # or with yarn:
  #- yarn install --cache-folder .yarn

eas-build:
  stage: build
  script:
    - apk add --no-cache bash
    - npx expo login -u "$USERNAME" -p $TOKEN
    - npx eas-cli build --platform all --non-interactive